// Event Types
// const SEND_WELCOME_EMAIL = 'SEND_WELCOME_EMAIL';
// const SEND_VERIFICATION_EMAIL = 'SEND_VERIFICATION_EMAIL';
// const SEND_VERIFICATION_SMS = 'SEND_VERITIFICATION_SMS';
const SEND_RESET_PASSWORD_EMAIL = 'SEND_RESET_PASSWORD_EMAIL';
const SEND_EVENT_REGISTRATION = 'SEND_EVENT_REGISTRATION';
const SEND_COMMON_EMAIL = 'SEND_COMMON_EMAIL';

export const EventTypes = {
  // SEND_WELCOME_EMAIL,
  // SEND_VERIFICATION_EMAIL,
  // SEND_VERIFICATION_SMS,
  SEND_RESET_PASSWORD_EMAIL,
  SEND_EVENT_REGISTRATION,
  SEND_COMMON_EMAIL,
};
